apiVersion: v1
kind: Service
metadata:
  name: clickhouse-service
spec:
  selector:
    app: clickhouse
  ports:
    - name: http
      protocol: TCP
      port: 8123
      targetPort: 8123
    - name: tcp
      protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
